"""
This type stub file was generated by pyright.
"""

from sklearn.covariance import EmpiricalCovariance as _sklearn_EmpiricalCovariance
from daal4py.sklearn._n_jobs_support import control_n_jobs
from daal4py.sklearn._utils import sklearn_check_version
from onedal.common.hyperparameters import get_hyperparameters
from ..._device_offload import wrap_output_data
from ..._utils import register_hyperparameters
from ...base import oneDALEstimator

@register_hyperparameters({ "fit": get_hyperparameters("covariance", "compute") })
@control_n_jobs(decorated_methods=["fit", "mahalanobis"])
class EmpiricalCovariance(oneDALEstimator, _sklearn_EmpiricalCovariance):
    __doc__ = ...
    if sklearn_check_version("1.2"):
        _parameter_constraints: dict = ...
    _onedal_covariance = ...
    _onedal_cpu_supported = ...
    _onedal_gpu_supported = ...
    def fit(self, X, y=...): # -> Self:
        ...
    
    @wrap_output_data
    def mahalanobis(self, X):
        ...
    
    error_norm = ...
    score = ...


