"""
This type stub file was generated by pyright.
"""

import os
from . import utils
from ._config import config_context, get_config, set_config
from .dispatcher import get_patch_map, get_patch_names, is_patched_instance, patch_sklearn, sklearn_is_patched, unpatch_sklearn
from onedal import _spmd_backend
from onedal.common.hyperparameters import get_hyperparameters
from ._utils import set_sklearn_ex_verbose

__all__ = ["basic_statistics", "cluster", "config_context", "covariance", "decomposition", "ensemble", "get_config", "get_hyperparameters", "get_patch_map", "get_patch_names", "is_patched_instance", "linear_model", "manifold", "metrics", "model_selection", "neighbors", "patch_sklearn", "set_config", "sklearn_is_patched", "svm", "unpatch_sklearn", "utils"]
__version__ = ...
onedal_iface_flag = ...
if onedal_iface_flag == "0":
    ...
