"""
This type stub file was generated by pyright.
"""

from daal4py.sklearn._utils import PatchingConditionsChain as daal4py_PatchingConditionsChain, sklearn_check_version
from sklearn.utils import get_tags

if sklearn_check_version("1.6"):
    ...
else:
    get_tags = ...
class PatchingConditionsChain(daal4py_PatchingConditionsChain):
    def get_status(self): # -> bool:
        ...
    
    def write_log(self, queue=..., transferred_to_host=...): # -> None:
        ...
    


def set_sklearn_ex_verbose(): # -> None:
    ...

def get_patch_message(s, queue=..., transferred_to_host=...): # -> LiteralString | Literal['running accelerated version on GPU', 'running accelerated version on CPU', 'fallback to original Scikit-learn']:
    ...

def get_sklearnex_version(rule): # -> bool:
    ...

def register_hyperparameters(hyperparameters_map): # -> Callable[..., Any]:
    """Decorator for hyperparameters support in estimator class.

    Adds `get_hyperparameters` method to class.

    Parameters
    ----------
    hyperparameters_map : dict
       Dictionary containing the operator-hyperparameter mapping.

    Returns
    -------
    decorator : function
        Function which adds `get_hyperparameters` method to classes.
    """
    ...

