"""
This type stub file was generated by pyright.
"""

from daal4py.sklearn._utils import sklearn_check_version
from dataclasses import dataclass
from sklearn.utils import Tags as _sklearn_Tags

if sklearn_check_version("1.6"):
    @dataclass
    class Tags(_sklearn_Tags):
        onedal_array_api: bool = ...
    
    
class oneDALEstimator:
    """Inherited class for all oneDAL-based estimators.

    This class must be inherited before any scikit-learn estimator
    classes (i.e. those which inherit from scikit-learn's BaseEstimator).

    It enables:

      - dispatching to oneDAL
      - html documentation

    Notes
    -----
    Sklearnex-only estimators must inherit this class directly before
    BaseEstimator in order to properly render documentation.  Other
    sklearn classes like Mixins can be before this class in the MRO
    without any impact on functionality.
    """
    if sklearn_check_version("1.6"):
        def __sklearn_tags__(self) -> Tags:
            ...
        
    else:
        ...
    if sklearn_check_version("1.4"):
        ...


