"""
This type stub file was generated by pyright.
"""

import pytest

def pytest_configure(config): # -> None:
    ...

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_call(item): # -> Generator[None, Any, None]:
    ...

@pytest.fixture
def with_sklearnex(): # -> Generator[None, Any, None]:
    ...

@pytest.fixture
def with_array_api(): # -> Generator[None, Any, None]:
    ...

@pytest.fixture
def without_allow_sklearn_after_onedal(): # -> Generator[None, Any, None]:
    ...

