"""
This type stub file was generated by pyright.
"""

from functools import lru_cache

@lru_cache(maxsize=None)
def get_patch_map_core(preview=...): # -> dict[str, list[list[Any]]]:
    ...

def get_patch_map(): # -> dict[str, list[list[Any]]]:
    ...

def get_patch_names(): # -> list[str]:
    ...

def patch_sklearn(name=..., verbose=..., global_patch=..., preview=...): # -> None:
    ...

def unpatch_sklearn(name=..., global_unpatch=...): # -> None:
    ...

def sklearn_is_patched(name=..., return_map=...): # -> dict[Any, Any] | Literal[True]:
    ...

def is_patched_instance(instance: object) -> bool:
    """Check if given instance is patched with scikit-learn-intelex.

    Parameters
    ----------
    instance : object
        Python object, usually a scikit-learn estimator instance.

    Returns
    -------
    Check : bool
        Boolean whether instance is a daal4py or sklearnex estimator.
    """
    ...

