"""
This type stub file was generated by pyright.
"""

from ..base import oneDALEstimator

class KNeighborsDispatchingBase(oneDALEstimator):
    def kneighbors_graph(self, X=..., n_neighbors=..., mode=...): # -> csr_matrix:
        ...
    


