"""
This type stub file was generated by pyright.
"""

from sklearn.neighbors._classification import KNeighborsClassifier as _sklearn_KNeighborsClassifier
from daal4py.sklearn._n_jobs_support import control_n_jobs
from daal4py.sklearn._utils import sklearn_check_version
from .._device_offload import wrap_output_data
from .common import KNeighborsDispatchingBase

@control_n_jobs(decorated_methods=["fit", "predict", "predict_proba", "kneighbors", "score"])
class KNeighborsClassifier(KNeighborsDispatchingBase, _sklearn_KNeighborsClassifier):
    __doc__ = ...
    if sklearn_check_version("1.2"):
        _parameter_constraints: dict = ...
    def __init__(self, n_neighbors=..., *, weights=..., algorithm=..., leaf_size=..., p=..., metric=..., metric_params=..., n_jobs=...) -> None:
        ...
    
    def fit(self, X, y): # -> Self:
        ...
    
    @wrap_output_data
    def predict(self, X): # -> Any:
        ...
    
    @wrap_output_data
    def predict_proba(self, X): # -> Any:
        ...
    
    @wrap_output_data
    def score(self, X, y, sample_weight=...): # -> Any:
        ...
    
    @wrap_output_data
    def kneighbors(self, X=..., n_neighbors=..., return_distance=...): # -> Any:
        ...
    


