"""
This type stub file was generated by pyright.
"""

from sklearn.neighbors._regression import KNeighborsRegressor as _sklearn_KNeighborsRegressor
from daal4py.sklearn._n_jobs_support import control_n_jobs
from daal4py.sklearn._utils import sklearn_check_version
from .._device_offload import wrap_output_data
from .common import KNeighborsDispatchingBase

@control_n_jobs(decorated_methods=["fit", "predict", "kneighbors", "score"])
class KNeighborsRegressor(KNeighborsDispatchingBase, _sklearn_KNeighborsRegressor):
    __doc__ = ...
    if sklearn_check_version("1.2"):
        _parameter_constraints: dict = ...
    def __init__(self, n_neighbors=..., *, weights=..., algorithm=..., leaf_size=..., p=..., metric=..., metric_params=..., n_jobs=...) -> None:
        ...
    
    def fit(self, X, y): # -> Self:
        ...
    
    @wrap_output_data
    def predict(self, X): # -> Any:
        ...
    
    @wrap_output_data
    def score(self, X, y, sample_weight=...): # -> Any:
        ...
    
    @wrap_output_data
    def kneighbors(self, X=..., n_neighbors=..., return_distance=...): # -> Any:
        ...
    


