"""
This type stub file was generated by pyright.
"""

from sklearn.neighbors._unsupervised import NearestNeighbors as _sklearn_NearestNeighbors
from sklearn.utils.validation import _deprecate_positional_args
from daal4py.sklearn._n_jobs_support import control_n_jobs
from daal4py.sklearn._utils import sklearn_check_version
from .._device_offload import wrap_output_data
from .common import KNeighborsDispatchingBase

@control_n_jobs(decorated_methods=["fit", "kneighbors", "radius_neighbors"])
class NearestNeighbors(KNeighborsDispatchingBase, _sklearn_NearestNeighbors):
    __doc__ = ...
    if sklearn_check_version("1.2"):
        _parameter_constraints: dict = ...
    @_deprecate_positional_args
    def __init__(self, n_neighbors=..., radius=..., algorithm=..., leaf_size=..., metric=..., p=..., metric_params=..., n_jobs=...) -> None:
        ...
    
    def fit(self, X, y=...): # -> Self:
        ...
    
    @wrap_output_data
    def kneighbors(self, X=..., n_neighbors=..., return_distance=...): # -> Any:
        ...
    
    @wrap_output_data
    def radius_neighbors(self, X=..., radius=..., return_distance=..., sort_results=...): # -> Any:
        ...
    
    def radius_neighbors_graph(self, X=..., radius=..., mode=..., sort_results=...): # -> Any:
        ...
    


