"""
This type stub file was generated by pyright.
"""

from sklearn.linear_model import LinearRegression as _sklearn_LinearRegression
from daal4py.sklearn._n_jobs_support import control_n_jobs
from daal4py.sklearn._utils import sklearn_check_version
from .._device_offload import wrap_output_data
from .._utils import register_hyperparameters
from ..base import oneDALEstimator
from onedal.common.hyperparameters import get_hyperparameters

if not sklearn_check_version("1.2"):
    ...
@register_hyperparameters({ "fit": get_hyperparameters("linear_regression", "train") })
@control_n_jobs(decorated_methods=["fit", "predict", "score"])
class LinearRegression(oneDALEstimator, _sklearn_LinearRegression):
    __doc__ = ...
    if sklearn_check_version("1.2"):
        _parameter_constraints: dict = ...
    else:
        def __init__(self, fit_intercept=..., normalize=..., copy_X=..., n_jobs=..., positive=...) -> None:
            ...
        
    def fit(self, X, y, sample_weight=...): # -> Self:
        ...
    
    @wrap_output_data
    def predict(self, X): # -> Any:
        ...
    
    @wrap_output_data
    def score(self, X, y, sample_weight=...): # -> Any:
        ...
    
    @property
    def coef_(self): # -> Any:
        ...
    
    @coef_.setter
    def coef_(self, value): # -> None:
        ...
    
    @coef_.deleter
    def coef_(self): # -> None:
        ...
    
    @property
    def intercept_(self): # -> Any:
        ...
    
    @intercept_.setter
    def intercept_(self, value): # -> None:
        ...
    
    @intercept_.deleter
    def intercept_(self): # -> None:
        ...
    


