"""
This type stub file was generated by pyright.
"""

from daal4py.sklearn._utils import daal_check_version
from sklearn.linear_model import LogisticRegression as _sklearn_LogisticRegression
from daal4py.sklearn._n_jobs_support import control_n_jobs
from .._device_offload import wrap_output_data
from ..base import oneDALEstimator

if daal_check_version((2024, "P", 1)):
    _sparsity_enabled = ...
    @control_n_jobs(decorated_methods=["fit", "predict", "predict_proba", "predict_log_proba", "score"])
    class LogisticRegression(oneDALEstimator, _sklearn_LogisticRegression):
        __doc__ = ...
        def __init__(self, penalty=..., *, dual=..., tol=..., C=..., fit_intercept=..., intercept_scaling=..., class_weight=..., random_state=..., solver=..., max_iter=..., multi_class=..., verbose=..., warm_start=..., n_jobs=..., l1_ratio=...) -> None:
            ...
        
        _onedal_cpu_fit = ...
        def fit(self, X, y, sample_weight=...): # -> Self:
            ...
        
        @wrap_output_data
        def predict(self, X): # -> Any:
            ...
        
        @wrap_output_data
        def predict_proba(self, X): # -> Any:
            ...
        
        @wrap_output_data
        def predict_log_proba(self, X): # -> Any:
            ...
        
        @wrap_output_data
        def score(self, X, y, sample_weight=...): # -> Any:
            ...
        
    
    
else:
    LogisticRegression = ...
