"""
This type stub file was generated by pyright.
"""

from daal4py.sklearn._utils import daal_check_version
from sklearn.linear_model import Ridge as _sklearn_Ridge
from daal4py.sklearn._n_jobs_support import control_n_jobs
from .._device_offload import wrap_output_data
from ..base import oneDALEstimator

if daal_check_version((2024, "P", 600)):
    @control_n_jobs(decorated_methods=["fit", "predict", "score"])
    class Ridge(oneDALEstimator, _sklearn_Ridge):
        __doc__ = ...
        def fit(self, X, y, sample_weight=...): # -> Self:
            ...
        
        @wrap_output_data
        def predict(self, X): # -> Any:
            ...
        
        @wrap_output_data
        def score(self, X, y, sample_weight=...): # -> Any:
            ...
        
        @property
        def coef_(self): # -> Any:
            ...
        
        @coef_.setter
        def coef_(self, value): # -> None:
            ...
        
        @property
        def intercept_(self): # -> Any:
            ...
        
        @intercept_.setter
        def intercept_(self, value): # -> None:
            ...
        
    
    
else:
    ...
