"""
This type stub file was generated by pyright.
"""

class _FuncWrapper:
    """Load the global configuration before calling the function."""
    def __init__(self, function) -> None:
        ...
    
    def with_config(self, config): # -> Self:
        ...
    
    def __call__(self, *args, **kwargs):
        ...
    


class _FuncWrapperOld:
    """Load the global configuration before calling the function."""
    def __init__(self, function) -> None:
        ...
    
    def __call__(self, *args, **kwargs):
        ...
    


