"""
This type stub file was generated by pyright.
"""

from sklearn.utils.validation import validate_data as _sklearn_validate_data
from daal4py.sklearn._utils import daal_check_version, sklearn_check_version
from daal4py.sklearn.utils.validation import add_dispatcher_docstring

if sklearn_check_version("1.6"):
    _finite_keyword = ...
else:
    _sklearn_validate_data = ...
    _finite_keyword = ...
if daal_check_version((2024, "P", 700)):
    ...
else:
    ...
def assert_all_finite(X, *, allow_nan=..., input_name=...): # -> None:
    ...

@add_dispatcher_docstring(_sklearn_validate_data)
def validate_data(_estimator, /, X=..., y=..., **kwargs): # -> tuple[Any, ...]:
    ...

