# main_config
test_mode: True

system_paths: 
  input_path:
    - input
    # - input2
    # - input3
    # - C:/Users/USER/Desktop/tickets_nuevo

  output_path:
    - D:/outputs/perfectocr
    - output"

  log_file_path:
    - D:/outputs/logs/perfectocr.txt
    - perfectocr.txt

logging_config:
  console_level: "INFO"
  console_format: "%(filename)s:%(lineno)d - %(message)s"
  file_level:  "INFO"
  file_format: "%(asctime)s - %(module)s:%(lineno)d - %(message)s"
  date_format: "%H:%M" #"%Y-%m-%d %H:%M:%S"
