# PerfectOCR/config/master_config.yaml
system:
  project_root: "C:/PerfectOCR"
  log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
# Todas las rutas del sistema
paths:
  input_folder: "C:/PerfectOCR/input"
  output_folder: "C:/PerfectOCR/output"
  
models_config:
  use_angle_cls: false
  lang: "es"
  show_log: false
  use_gpu: false
  enable_mkldnn: true
  rec_batch_num: 64
  models:
    det_model_dir: "C:/PerfectOCR/data/models/paddle/det/es"
    rec_model_dir: "C:/PerfectOCR/data/models/paddle/rec/es"
    cls_model_dir: "C:/PerfectOCR/data/models/paddle/cls"
    
pipeline_secuence:
  image_preparation:
    - "cleaner"           
    - "angle_corrector" 
    - "geometry_detection"  
    - "line_reconstructor" 
    - "polygon_extractor" 
  
  preprocessing_stage:
    - "moire"
    - "sp"
    - "gauss"
    - "clahe"
    - "sharp"
    - "binarizator"
    - "fragmentator"
  
# Configuración de salida (independiente)
enabled_outputs:
  pre_clean: false
  angle_corrected: false
  preprocessed_image: false
  ocr_raw: false
  cropped_img: false
  moire_poly: false
  sp_poly: false
  gauss_poly: false
  clahe_poly: false
  sharp_poly: false
  binarized_polygons: false
  problematic_polygons: false
  reconstructed_lines: false
  table_lines: false
  table_structured: false
  math_max_corrected: true

# Configuración de procesamiento
processing:
  max_workers: 4
  valid_image_extensions: [.png, .jpg, .jpeg, .bmp, .tif, .tiff, .webp, .gif, .pbm, .pgm, .ppm, .jp2, .ico]
  
  batch_mode: true
  batch_processing:
    small_batch_limit: 5
    max_physical_cores: 4
    add_extra_worker: true
    batch_size_factor: 2
    auto_mode: true
    
# Configuración específica de cada módulo (SIN rutas)
modules:
  image_loader:
    deskew:
      min_angle_for_correction: 0.15
      canny_thresholds: [50, 150]
      hough_threshold: 150
      hough_min_line_length_cap_px: 300
      hough_max_line_gap_px: 20
      hough_angle_filter_range_degrees: [-20.0, 20.0]
      
    cleaning:
      std_low: 15.0
      sp_thr: 0.015
      clahe_clip: 2.0    
      clahe_grid: [8, 8]
      
    cutting:
      cropping_padding: 5

  preprocessing:
    moire:
        mode:
          percentile:
            percentile_threshold: 98
            notch_radius: 2
            min_distance_from_center: 200
          factor:
            mean_factor_threshold: 4
          absolute:
            absolute_threshold: 200000000
    median_filter:
      kernel_size: 3
      salt_pepper_threshold: 0.0010
      salt_pepper_low: 2
      salt_pepper_high: 253

    bilateral_params:
      laplacian_variance_threshold: 80.0
      d: 9
      sigma_color: 75
      sigma_space: 75
      
    contrast:
      general:
        clahe_clip_limit: 2.0
        dimension_thresholds_px: [1000, 2500, 4000]
        grid_sizes_map: [[6, 6], [8, 8], [10, 10]]
      local:
        window_size: 100
        std_dev_threshold: 15.0
    
    sharpening:
      sharpness_threshold: 50.0
      radius: 1.0
      amount: 1.5
        
  ocr:
    text_cleaner:
      min_confidence: 70.0
    
    binarizator:
      c_value: 7
      height_thresholds_px: [100, 800, 1500, 2500]
      block_sizes_map: [15, 21, 25, 35, 41]
      
      quality:
        quality_min: 0.05
        quality_max: 0.95
    
    fragmentation:
      min_contour_area: 0.001
      density_std_factor: 2.0
      approx_poly_epsilon: 0.005

  vectorization:
    lineal:
      overlap: 0.3
    
    dbscan:
      min_cluster_size: 2
      eps: 1.0
      max_numbers_header: 2
      min_density_header: 50
      max_word_ratio_header: 0.8
      width_tolerance_header: 0.15
      max_search_lines_up: 2
      
    data_finder:
      wordfinder_model_path: "C:/PerfectOCR/data/models/word_finder/word_finder_model.pkl"
    
    math_max:
      total_mtl_abs_tolerance: 0.05
      row_relative_tolerance: 0.05
      
      