# config/master_config.yaml
pipeline_secuence:
  imagepre_stage:
    - "image_loader"
    - "cleaner"
    #- "angle_corrector"
    - "geometry_detector"
    - "polygon_extractor"

  preprocessing_stage:
     - "moire"
     - "sp"
     - "gauss"
    #  - "ink_enhancement"
     - "clahe"
     - "sharp"

  ocr_stage:
    - "paddle_wrapper"
    - "text_refiner"
    - "data_finder"
    
  vector_stage:
    - "lineal"
    - "vectorizer"
    - "dbscan"
    - "cos_sim"
    - "table_structurer"
    # - "table_validated"
    # - "math_max"

# Configuración de salida (independiente)
enabled_outputs:
  pre_clean: false
  angle_corrected: false
  preprocessed_image: false
  cropped_img: false
  discarded_polys: true
  moire_poly: false
  sp_poly: false
  gauss_poly: false
  ink_poly: false
  clahe_poly: false
  sharp_poly: false
  binarized_polygons: false
  ocr_raw: false
  reconstructed_lines: false
  semantic_field: false
  table_lines: false
  encoded_lines: false
  features: false
  image_features: false
  table_structured: false
  math_max_corrected: false
  
models_config:
  use_angle_cls: false
  lang: "es"
  show_log: false
  use_gpu: false
  enable_mkldnn: true
  rec_batch_num: 64
  det_model_dir: C:/PerfectOCR/data/models/paddle/det/es
  rec_model_dir: C:/PerfectOCR/data/models/paddle/rec/es
  cls_model_dir: C:/PerfectOCR/data/models/paddle/cls
  model_path: C:/word_finder_model/models/wf_model.pkl
  
# Configuración de procesamiento
processing:
  max_workers: 1
  valid_image_extensions: [.png, .jpg, .jpeg, .bmp, .tif, .tiff, .webp, .gif, .pbm, .pgm, .ppm, .jp2, .ico]
  batch_mode: true
  small_batch_limit: 5
  max_physical_cores: 4
  add_extra_worker: true
  batch_size_factor: 2
  auto_mode: true

# Configuración específica de cada módulo (SIN rutas)
modules:
  image_preparation:
  
    angle_corrector:
      min_angle_for_correction: 0.15
      canny_thresholds: [50, 150]
      hough_threshold: 150
      hough_min_line_length_cap_px: 300
      hough_max_line_gap_px: 20
      hough_angle_filter_range_degrees: [-20.0, 20.0]
        
    cleaner:
      std_low: 15.0
      sp_thr: 0.0125
      clahe_clip: 2.0
      clahe_grid: [6, 6]
      kernel_size: 3
    
    polygon_extractor:
      cropping_padding: 1
      bin_interval: [10, 250]
      percentil: 0.5
      angle_thr: [44.5, 45.5]

  preprocessing:
    moire:
      min_distance_from_center: 200
      notch_radius: 2
      percentile_threshold: 90
      mean_factor_threshold: 4
      absolute_threshold: 200000000

    sp_config:
      kernel_size: 3
      salt_pepper_threshold: 0.0015
      salt_pepper_low: 15
      salt_pepper_high: 253
      sobel_threshold: 0.85

    gauss_params:
      laplacian_variance_threshold: 80.0
      d: 9
      sigma_color: 75
      sigma_space: 75

    ink_enhancement:
      faded_detection_threshold: 0.4
      contrast_boost_factor: 1.5

    contrast:
      clahe_clip_limit: 2.0
      contrast_threshold: 50
      dimension_thresholds_px: [1000, 2500, 4000]
      grid_sizes_map: [[6, 6], [8, 8], [10, 10]]
      window_size: 100
      std_dev_threshold: 15.0
    
    sharpening:
      sharpness_threshold: 50.0
      radius: 1.0
      amount: 1.5
        
  ocr:
    paddle_wrapper:
      min_confidence: 65.0

    fragmenter:
      c_value: 7
      height_thresholds_px: [100, 800, 1500, 2500]
      block_sizes_map: [15, 21, 25, 35, 41]
      min_blobs_for_frag: 3
      gap_threshold_norm: 0.01
      min_area_factor: 0.01
      
    text_refiner:
      num_passes: 1
  
    text_cleaner:
      min_probability: 75.0
      min_char: 2.0
      min_confidence: 70.0
      min_conf_to_clean: 90.0
    
    semantic_clasificator:
      semantic_range: [45.0, 66.5] # Cantidad de digitos
      encode_mean: [25.1, 39.1] # Promedio de densidad
      morph_mean: [-0.3, 0.35] # Promedio morfológico
        
    data_finder:
      wordfinder_model_path: C:/word_finder_model/models/wf_model.pkl
      min_similarity: 0.92
      max_q_lenght: 20

    text_corrector:
      confidence_threshold: 0.90
    
  vectorization:
    lineal:
      overlap_threshold: 0.50
      
    vectorizer:
      keywords_interval_enabled: false
      exclude_types: [
        "descriptive",
        "code", 
        "umd"
      ]
      include_types: [
        "numeric", 
        "quantitative"
      ]
      
    dbscan:
      eps: 1.0
      min_cluster_size: 2
      hmin_cluster_size: 3

    cos_sim:
      min_cluster: 1
      similarity_threshold: 0.90
      emergency_threshold: 0.80
      interval: 2
      dummie_weights: [0.35, 0.65]
    
    table_structurer:
      min_h: 3

    math_max:
      total_mtl_abs_tolerance: 0.05
      row_relative_tolerance: 0.05
