# PerfectOCR/config/master_config.yaml
system:
  project_root: "C:/PerfectOCR"
  log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
# Todas las rutas del sistema
paths:
  input_folder: "C:/PerfectOCR/input2"
  output_folder: "C:/PerfectOCR/output"
  db_path: "C:/PerfectOCR/data_base/data_base.json"
  
models_config:
  use_angle_cls: false
  lang: "es"
  show_log: false
  use_gpu: false
  enable_mkldnn: true
  rec_batch_num: 32
  models:
    det_model_dir: "C:/PerfectOCR/data/models/paddle/det/es"
    rec_model_dir: "C:/PerfectOCR/data/models/paddle/rec/es"
    cls_model_dir: "C:/PerfectOCR/data/models/paddle/cls"
    wordfinder_model_path: "C:/word_finder_model/data/word_finder_model.pkl"
    
pipeline_secuence:
  imagepre_stage:
    # - "dummie"
    - "image_loader"
    # - "cleaner"
    # - "angle_corrector"
    - "geometry_detector"
    - "polygon_extractor"

  preprocessing_stage:
    - "dummie"
    # - "moire"
    # - "sp"
    # - "gauss"
    # - "ink_enhancement"
    # - "clahe"
    # - "sharp"
    # - "binarizator"

  ocr_stage:
    # - "dummie"
    - "paddle_wrapper"
    - "text_refiner"
    - "data_finder"
    
  vector_stage:
    # - "dummie"
    - "lineal"
    - "vectorizer"
    # - "dbscan"
    # - "cos_sim"
    # - "table_structurer"
    # - "semantic_corrector"
    # - "math_max"
  
# Configuración de salida (independiente)
enabled_outputs:
  pre_clean: false
  angle_corrected: false
  preprocessed_image: false
  cropped_img: false
  moire_poly: false
  sp_poly: false
  gauss_poly: false
  ink_poly: false
  clahe_poly: false
  sharp_poly: false
  binarized_polygons: false
  ocr_raw: false
  reconstructed_lines: false
  table_lines: false
  table_structured: false
  math_max_corrected: false

# Configuración de procesamiento
processing:
  max_workers: 1
  valid_image_extensions: [.png, .jpg, .jpeg, .bmp, .tif, .tiff, .webp, .gif, .pbm, .pgm, .ppm, .jp2, .ico]
  batch_mode: true
  batch_processing:
    small_batch_limit: 5
    max_physical_cores: 4
    add_extra_worker: true
    batch_size_factor: 2
    auto_mode: true

# Configuración específica de cada módulo (SIN rutas)
modules:
  image_preparation:
    cleaner:
        std_low: 15.0
        sp_thr: 0.015
        clahe_clip: 2.0
        clahe_grid: [8, 8]

    angle_corrector:
      min_angle_for_correction: 0.15
      canny_thresholds: [50, 150]
      hough_threshold: 150
      hough_min_line_length_cap_px: 300
      hough_max_line_gap_px: 20
      hough_angle_filter_range_degrees: [-20.0, 20.0]
        
    polygon_extractor:
      cropping_padding: 5

  preprocessing:
    moire:
      percentile:
        percentile_threshold: 95
        notch_radius: 2
        min_distance_from_center: 200

      factor:
        mean_factor_threshold: 4

      absolute:
        absolute_threshold: 200000000

    sp_config:
      kernel_size: 5
      salt_pepper_threshold: 0.0025
      salt_pepper_low: 3
      salt_pepper_high: 253

    gauss_params:
      laplacian_variance_threshold: 80.0
      d: 9
      sigma_color: 75
      sigma_space: 75

    ink_enhancement:
      faded_detection_threshold: 0.4
      contrast_boost_factor: 1.5

    contrast:
      general:
        clahe_clip_limit: 2.0
        dimension_thresholds_px: [1000, 2500, 4000]
        grid_sizes_map: [[6, 6], [8, 8], [10, 10]]

      local:
        window_size: 100
        std_dev_threshold: 15.0
    
    sharpening:
      sharpness_threshold: 50.0
      radius: 1.0
      amount: 1.5
      
    binarizator:
      c_value: 7
      height_thresholds_px: [100, 800, 1500, 2500]
      block_sizes_map: [15, 21, 25, 35, 41]
      
      quality:
        quality_min: 0.10
        quality_max: 0.90
        
  ocr:
    paddle_wrapper: 
      min_confidence: 60.0

    text_refiner:
      num_passes: 2
  
    text_cleaner:
      min_confidence: 75.0
      min_probability: 75.0
      min_char: 2
    
    semantic_clasificator:
      numeric: [100.0, 66.0]
      code: [45.0, 65.9]
      descriptive: [0.0, 44.9]
        
    data_finder:
      wordfinder_model_path: C:/word_finder_model/data/word_finder_model.pkl
      min_similarity: 0.85
      max_q_lenght: 20

    fragmenter:
      fragment_on_text: True
      min_contours_for_frag: 2

    text_corrector:
      confidence_threshold: 0.90
  
  vectorization:
    lineal:
      overlap_threshold: 0.35
      
    vectorizer:
      vectotize: True

    cos_sim:
      min_cluster: 1
      similarity_threshold: 0.85
      interval: 1
      
    dbscan:
      eps: 1.0
      min_cluster_size: 2

    table_structurer:
      min_h: 3
      min_cosine_similarity: 0.65
    
    math_max:
      total_mtl_abs_tolerance: 0.05
      row_relative_tolerance: 0.05