# config/master_config.yaml
pipeline_secuence:
  imagepre_stage:
    - "image_loader"
    - "angle_corrector"
    # - "ink_enhancement"
    - "geometry_detector"
    - "polygon_extractor"

  preprocessing_stage:
    # - restorer
    # - "moire"
    # - "sp"
    # - "gauss"
    # - "clahe"
    # - "sharp"

  ocr_stage:
    - "paddle_wrapper"
    - "text_refiner"
    - "data_finder"
    
  vector_stage:
   - "lineal"
   - "cos_sim"
   - "table_structurer"
  #  - "math_max"
   
log_debug:
  text_ocr: False
  key_fields: False
  lines: False
  table_lines: False
  table_geo: False
  table_correct: True
  
  semantic_types_log: [2, 3, 4, 5]
  kf_list_log: [6]
  
# Configuración de salida
enabled_outputs:
  image_load_outputs:
    full_img: False
    bin_full_img: False
    angle_corrected: False
    moire_poly: False
    cropped_img: False
    final_polys: False
    discarded_polys: False
    deleted_polys: False
    opened: False
  
  preprocessing_outputs:
    sp_poly: False
    gauss_poly: False
    clahe_poly: False
    sharp_poly: False

  ocr_outputs:
    ocr_raw: False
    binarized_polygons: False
    cropp_blobs: False
    fragmented_polys: False
    semantic_field: False
    seman_clas: False
    cleanned_text: False
  
  vectorization_outputs:
    reconstructed_lines: False
    table_lines: False
    features: False
    image_features: False
    table_structured: False
    math_max_corrected: False

models_config:
  use_angle_cls: False
  lang: "es"
  show_log: False
  use_gpu: False
  enable_mkldnn: True
  rec_batch_num: 32
  cpu_threads: 3
  max_batch_size: 32
  det_limit_side_len: 1280
  det_db_score_mode: 'slow'
  table: False
  use_mp: True
  max_text_length: 20
  rec_image_inverse: False
  
  det_model_dir: "C:/PerfectOCR/data/models/paddle/det/es"
  rec_model_dir: "C:/PerfectOCR/data/models/paddle/rec/es"
  wf_model_path: "C:/PerfectOCR/data/models/wf/wf_model.pkl"
  set_wf_params: False
  
modules:
  image_preparation:
    ink_enhancement:
      white: [255, 255, 255]
      black: [0, 0, 0]
      aspect_ratio_range: [2.5, 13.8]
      angle_threshold: 41.25
      thr: 0.23
      black_thr: 0.726
      solid_thr: 0.95
      shape_thr: 0.327
      
    angle_corrector:
      min_angle_for_correction: 0.9
      canny_thresholds: [70, 120]
      hough_threshold: 150
      hough_min_line_length_cap_px: 250
      hough_max_line_gap_px: 20
      hough_angle_filter_range_degrees: [-22.5, 22.5]
      border_cutt: 100
      border_color: [255, 255, 255]
      
    geometry_detect:
      morph_kernel: [2, 2]
      iterations: 2

    polygon_extractor:
      cropping_padding: 1.0

  preprocessing:
    restorer:
      area_threshold: 12
      kernel_threshold: 3

    moire:
      min_distance_from_center: 150
      notch_radius: 3
      percentile_threshold: 96
      mean_factor: 4
      abs_threshold: 20000000

    sp_config:
      kernel_size: 3
      salt_pepper_threshold: 0.015
      salt_pepper_low: 10
      salt_pepper_high: 250
      sobel_threshold: 0.85

    gauss_params:
      laplacian_variance_threshold: 80.0

    contrast:
      clahe_clip_limit: 2.0
      contrast_threshold: 50
      dimension_thresholds_px: [1000, 2500, 4000]
      grid_sizes_map: [[6, 6], [8, 8], [10, 10]]
    
    sharpening:
      sharpness_threshold: 50.0
      kernel: 3
        
  ocr:
    paddle_wrapper:
      min_confidence: 0.5307
      
    text_refiner:
      num_passes: 1
      encode_mean: [23.7, 105.7] # Promedio de densidad
      morph_mean: [-0.297, 0.337] # Promedio morfológico
  
    text_cleaner:
      min_probability: 75.0
    
  vectorization:
    lineal:
      get_vectors: True
      overlap_threshold: 0.596
      
    cos_sim:
      metric: "euclidean"
      eps: 0.97
      min_cluster: 2
      similarity_threshold: 0.901
      emergency_threshold: 0.83
      dummie_weights: [0.35, 0.65]
    
    table_structurer:
      min_h: 3

    math_max:
      total_mtl_abs_tolerance: 0.15
      row_relative_tolerance: 0.10

utils:
  valid_image_extensions: ['.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.tif', '.webp', '.pbm', '.pgm', '.ppm', '.jp2']
  dpi_range: [100, 200, 300, 400, 600, 1200]
  bin_interval: [10, 245]
  percentile: [0.10, 0.99]
  