"""
This type stub file was generated by pyright.
"""

from .._utils import get_sklearnex_version
from .nusvc import NuSVC
from .nusvr import NuSVR
from .svc import SVC
from .svr import SVR
from daal4py.sklearn.svm import SVC

if get_sklearnex_version((2021, "P", 300)):
    ...
else:
    ...
