"""
This type stub file was generated by pyright.
"""

from ..base import oneDALEstimator

class BaseSVM(oneDALEstimator):
    @property
    def intercept_(self):
        ...
    
    @intercept_.setter
    def intercept_(self, value): # -> None:
        ...
    
    @intercept_.deleter
    def intercept_(self): # -> None:
        ...
    


class BaseSVC(BaseSVM):
    ...


class BaseSVR(BaseSVM):
    ...


