"""
This type stub file was generated by pyright.
"""

from sklearn.svm import SVR as _sklearn_SVR
from sklearn.utils.validation import _deprecate_positional_args
from daal4py.sklearn._n_jobs_support import control_n_jobs
from daal4py.sklearn._utils import sklearn_check_version
from .._device_offload import wrap_output_data
from ._common import BaseSVR

@control_n_jobs(decorated_methods=["fit", "predict", "score"])
class SVR(BaseSVR, _sklearn_SVR):
    __doc__ = ...
    if sklearn_check_version("1.2"):
        _parameter_constraints: dict = ...
    @_deprecate_positional_args
    def __init__(self, *, kernel=..., degree=..., gamma=..., coef0=..., tol=..., C=..., epsilon=..., shrinking=..., cache_size=..., verbose=..., max_iter=...) -> None:
        ...
    
    def fit(self, X, y, sample_weight=...): # -> Self:
        ...
    
    @wrap_output_data
    def predict(self, X): # -> Any:
        ...
    
    @wrap_output_data
    def score(self, X, y, sample_weight=...): # -> Any:
        ...
    


