"""
This type stub file was generated by pyright.
"""

from daal4py.sklearn._utils import daal_check_version
from daal4py.sklearn._n_jobs_support import control_n_jobs
from .._device_offload import wrap_output_data
from .._utils import register_hyperparameters
from ..base import oneDALEstimator
from sklearn.decomposition import PCA as _sklearn_PCA
from onedal.common.hyperparameters import get_hyperparameters

if daal_check_version((2024, "P", 100)):
    @register_hyperparameters({ "fit": get_hyperparameters("pca", "train") })
    @control_n_jobs(decorated_methods=["fit", "transform", "fit_transform"])
    class PCA(oneDALEstimator, _sklearn_PCA):
        __doc__ = ...
        def fit(self, X, y=...): # -> Self:
            ...
        
        @wrap_output_data
        def transform(self, X): # -> Any:
            ...
        
        def fit_transform(self, X, y=...):
            ...
        
        def inverse_transform(self, X): # -> NDArray[bool_] | Any | DataFrame:
            ...
        
    
    
else:
    ...
