"""
This type stub file was generated by pyright.
"""

from sklearn.decomposition import IncrementalPCA as _sklearn_IncrementalPCA
from daal4py.sklearn._n_jobs_support import control_n_jobs
from ..._device_offload import wrap_output_data
from ...base import oneDALEstimator

@control_n_jobs(decorated_methods=["fit", "partial_fit", "transform", "_onedal_finalize_fit"])
class IncrementalPCA(oneDALEstimator, _sklearn_IncrementalPCA):
    _need_to_finalize_attrs = ...
    def __init__(self, n_components=..., *, whiten=..., copy=..., batch_size=...) -> None:
        ...
    
    _onedal_incremental_pca = ...
    _onedal_cpu_supported = ...
    _onedal_gpu_supported = ...
    def __getattr__(self, attr): # -> Any:
        ...
    
    def partial_fit(self, X, y=..., check_input=...): # -> Self:
        ...
    
    def fit(self, X, y=...): # -> Self:
        ...
    
    @wrap_output_data
    def transform(self, X): # -> Any:
        ...
    
    @wrap_output_data
    def fit_transform(self, X, y=..., **fit_params): # -> Any:
        ...
    
    __doc__ = ...


