"""
This type stub file was generated by pyright.
"""

def get_patch_str(name=..., verbose=...): # -> str:
    ...

def get_patch_str_re(): # -> LiteralString:
    ...

def patch_sklearn_global(name=..., verbose=...): # -> None:
    ...

def unpatch_sklearn_global(): # -> None:
    ...

