"""
This type stub file was generated by pyright.
"""

from sklearn.cluster import DBSCAN as _sklearn_DBSCAN
from daal4py.sklearn._n_jobs_support import control_n_jobs
from daal4py.sklearn._utils import sklearn_check_version
from ..base import oneDALEstimator

if sklearn_check_version("1.1") and not sklearn_check_version("1.2"):
    ...
class BaseDBSCAN(oneDALEstimator):
    ...


@control_n_jobs(decorated_methods=["fit"])
class DBSCAN(BaseDBSCAN, _sklearn_DBSCAN):
    __doc__ = ...
    if sklearn_check_version("1.2"):
        _parameter_constraints: dict = ...
    def __init__(self, eps=..., *, min_samples=..., metric=..., metric_params=..., algorithm=..., leaf_size=..., p=..., n_jobs=...) -> None:
        ...
    
    def fit(self, X, y=..., sample_weight=...): # -> Self:
        ...
    


