"""
This type stub file was generated by pyright.
"""

from daal4py.sklearn._utils import daal_check_version
from sklearn.cluster import KMeans as _sklearn_KMeans
from daal4py.sklearn._n_jobs_support import control_n_jobs
from .._device_offload import wrap_output_data
from ..base import oneDALEstimator

if daal_check_version((2023, "P", 200)):
    @control_n_jobs(decorated_methods=["fit", "fit_transform", "predict", "score"])
    class KMeans(oneDALEstimator, _sklearn_KMeans):
        __doc__ = ...
        def __init__(self, n_clusters=..., *, init=..., n_init=..., max_iter=..., tol=..., verbose=..., random_state=..., copy_x=..., algorithm=...) -> None:
            ...
        
        def fit(self, X, y=..., sample_weight=...): # -> Self:
            ...
        
        _onedal_gpu_supported = ...
        _onedal_cpu_supported = ...
        _transform = ...
        @wrap_output_data
        def score(self, X, y=..., sample_weight=...): # -> Any:
            ...
        
    
    
else:
    ...
